/*
 * This file is generated by jOOQ.
 */
package jslx.dbutilities.jsldbsrc;


import jslx.dbutilities.jsldbsrc.tables.AcrossRepStat;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in JSL_DB.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ARS_ME_FK_INDEX = Internal.createIndex(DSL.name("ARS_ME_FK_INDEX"), AcrossRepStat.ACROSS_REP_STAT, new OrderField[] { AcrossRepStat.ACROSS_REP_STAT.SIM_RUN_ID_FK, AcrossRepStat.ACROSS_REP_STAT.ELEMENT_ID_FK }, true);
}
