/*
 * This file is generated by jOOQ.
 */
package jslx.dbutilities.jsldbsrc;


import java.util.Arrays;
import java.util.List;

import jslx.dbutilities.jsldbsrc.tables.AcrossRepStat;
import jslx.dbutilities.jsldbsrc.tables.AcrossRepView;
import jslx.dbutilities.jsldbsrc.tables.BatchStat;
import jslx.dbutilities.jsldbsrc.tables.BatchStatView;
import jslx.dbutilities.jsldbsrc.tables.ModelElement;
import jslx.dbutilities.jsldbsrc.tables.PwDiffWithinRepView;
import jslx.dbutilities.jsldbsrc.tables.SimulationRun;
import jslx.dbutilities.jsldbsrc.tables.WithinRepCounterStat;
import jslx.dbutilities.jsldbsrc.tables.WithinRepCounterView;
import jslx.dbutilities.jsldbsrc.tables.WithinRepResponseView;
import jslx.dbutilities.jsldbsrc.tables.WithinRepStat;
import jslx.dbutilities.jsldbsrc.tables.WithinRepView;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JslDb extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>JSL_DB</code>
     */
    public static final JslDb JSL_DB = new JslDb();

    /**
     * The table <code>JSL_DB.ACROSS_REP_STAT</code>.
     */
    public final AcrossRepStat ACROSS_REP_STAT = AcrossRepStat.ACROSS_REP_STAT;

    /**
     * The table <code>JSL_DB.ACROSS_REP_VIEW</code>.
     */
    public final AcrossRepView ACROSS_REP_VIEW = AcrossRepView.ACROSS_REP_VIEW;

    /**
     * The table <code>JSL_DB.BATCH_STAT</code>.
     */
    public final BatchStat BATCH_STAT = BatchStat.BATCH_STAT;

    /**
     * The table <code>JSL_DB.BATCH_STAT_VIEW</code>.
     */
    public final BatchStatView BATCH_STAT_VIEW = BatchStatView.BATCH_STAT_VIEW;

    /**
     * The table <code>JSL_DB.MODEL_ELEMENT</code>.
     */
    public final ModelElement MODEL_ELEMENT = ModelElement.MODEL_ELEMENT;

    /**
     * The table <code>JSL_DB.PW_DIFF_WITHIN_REP_VIEW</code>.
     */
    public final PwDiffWithinRepView PW_DIFF_WITHIN_REP_VIEW = PwDiffWithinRepView.PW_DIFF_WITHIN_REP_VIEW;

    /**
     * The table <code>JSL_DB.SIMULATION_RUN</code>.
     */
    public final SimulationRun SIMULATION_RUN = SimulationRun.SIMULATION_RUN;

    /**
     * The table <code>JSL_DB.WITHIN_REP_COUNTER_STAT</code>.
     */
    public final WithinRepCounterStat WITHIN_REP_COUNTER_STAT = WithinRepCounterStat.WITHIN_REP_COUNTER_STAT;

    /**
     * The table <code>JSL_DB.WITHIN_REP_COUNTER_VIEW</code>.
     */
    public final WithinRepCounterView WITHIN_REP_COUNTER_VIEW = WithinRepCounterView.WITHIN_REP_COUNTER_VIEW;

    /**
     * The table <code>JSL_DB.WITHIN_REP_RESPONSE_VIEW</code>.
     */
    public final WithinRepResponseView WITHIN_REP_RESPONSE_VIEW = WithinRepResponseView.WITHIN_REP_RESPONSE_VIEW;

    /**
     * The table <code>JSL_DB.WITHIN_REP_STAT</code>.
     */
    public final WithinRepStat WITHIN_REP_STAT = WithinRepStat.WITHIN_REP_STAT;

    /**
     * The table <code>JSL_DB.WITHIN_REP_VIEW</code>.
     */
    public final WithinRepView WITHIN_REP_VIEW = WithinRepView.WITHIN_REP_VIEW;

    /**
     * No further instances allowed
     */
    private JslDb() {
        super("JSL_DB", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            AcrossRepStat.ACROSS_REP_STAT,
            AcrossRepView.ACROSS_REP_VIEW,
            BatchStat.BATCH_STAT,
            BatchStatView.BATCH_STAT_VIEW,
            ModelElement.MODEL_ELEMENT,
            PwDiffWithinRepView.PW_DIFF_WITHIN_REP_VIEW,
            SimulationRun.SIMULATION_RUN,
            WithinRepCounterStat.WITHIN_REP_COUNTER_STAT,
            WithinRepCounterView.WITHIN_REP_COUNTER_VIEW,
            WithinRepResponseView.WITHIN_REP_RESPONSE_VIEW,
            WithinRepStat.WITHIN_REP_STAT,
            WithinRepView.WITHIN_REP_VIEW);
    }
}
