/*
 * This file is generated by jOOQ.
 */
package jslx.dbutilities.jsldbsrc;


import jslx.dbutilities.jsldbsrc.tables.AcrossRepStat;
import jslx.dbutilities.jsldbsrc.tables.BatchStat;
import jslx.dbutilities.jsldbsrc.tables.ModelElement;
import jslx.dbutilities.jsldbsrc.tables.SimulationRun;
import jslx.dbutilities.jsldbsrc.tables.WithinRepCounterStat;
import jslx.dbutilities.jsldbsrc.tables.WithinRepStat;
import jslx.dbutilities.jsldbsrc.tables.records.AcrossRepStatRecord;
import jslx.dbutilities.jsldbsrc.tables.records.BatchStatRecord;
import jslx.dbutilities.jsldbsrc.tables.records.ModelElementRecord;
import jslx.dbutilities.jsldbsrc.tables.records.SimulationRunRecord;
import jslx.dbutilities.jsldbsrc.tables.records.WithinRepCounterStatRecord;
import jslx.dbutilities.jsldbsrc.tables.records.WithinRepStatRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * JSL_DB.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AcrossRepStatRecord> SQL0000000095_736A8145_0179_91C9_A2FA_00000F317028 = Internal.createUniqueKey(AcrossRepStat.ACROSS_REP_STAT, DSL.name("SQL0000000095-736a8145-0179-91c9-a2fa-00000f317028"), new TableField[] { AcrossRepStat.ACROSS_REP_STAT.ID }, true);
    public static final UniqueKey<BatchStatRecord> SQL0000000107_06B1817D_0179_91C9_A2FA_00000F317028 = Internal.createUniqueKey(BatchStat.BATCH_STAT, DSL.name("SQL0000000107-06b1817d-0179-91c9-a2fa-00000f317028"), new TableField[] { BatchStat.BATCH_STAT.ID }, true);
    public static final UniqueKey<ModelElementRecord> ME_NAME_UNIQUE = Internal.createUniqueKey(ModelElement.MODEL_ELEMENT, DSL.name("ME_NAME_UNIQUE"), new TableField[] { ModelElement.MODEL_ELEMENT.SIM_RUN_ID_FK, ModelElement.MODEL_ELEMENT.ELEMENT_NAME }, true);
    public static final UniqueKey<ModelElementRecord> ME_PRIM_KY = Internal.createUniqueKey(ModelElement.MODEL_ELEMENT, DSL.name("ME_PRIM_KY"), new TableField[] { ModelElement.MODEL_ELEMENT.SIM_RUN_ID_FK, ModelElement.MODEL_ELEMENT.ELEMENT_ID }, true);
    public static final UniqueKey<SimulationRunRecord> SQL0000000081_7FA040FF_0179_91C9_A2FA_00000F317028 = Internal.createUniqueKey(SimulationRun.SIMULATION_RUN, DSL.name("SQL0000000081-7fa040ff-0179-91c9-a2fa-00000f317028"), new TableField[] { SimulationRun.SIMULATION_RUN.ID }, true);
    public static final UniqueKey<SimulationRunRecord> SR_NAME_EXP_UNIQUE = Internal.createUniqueKey(SimulationRun.SIMULATION_RUN, DSL.name("SR_NAME_EXP_UNIQUE"), new TableField[] { SimulationRun.SIMULATION_RUN.SIM_NAME, SimulationRun.SIMULATION_RUN.EXP_NAME }, true);
    public static final UniqueKey<WithinRepCounterStatRecord> SQL0000000102_C5044162_0179_91C9_A2FA_00000F317028 = Internal.createUniqueKey(WithinRepCounterStat.WITHIN_REP_COUNTER_STAT, DSL.name("SQL0000000102-c5044162-0179-91c9-a2fa-00000f317028"), new TableField[] { WithinRepCounterStat.WITHIN_REP_COUNTER_STAT.ID }, true);
    public static final UniqueKey<WithinRepCounterStatRecord> WRCS_UNIQUE_ELEMENT_SIMRUN_REPNUM = Internal.createUniqueKey(WithinRepCounterStat.WITHIN_REP_COUNTER_STAT, DSL.name("WRCS_UNIQUE_ELEMENT_SIMRUN_REPNUM"), new TableField[] { WithinRepCounterStat.WITHIN_REP_COUNTER_STAT.ELEMENT_ID_FK, WithinRepCounterStat.WITHIN_REP_COUNTER_STAT.SIM_RUN_ID_FK, WithinRepCounterStat.WITHIN_REP_COUNTER_STAT.REP_NUM }, true);
    public static final UniqueKey<WithinRepStatRecord> SQL0000000089_62A30128_0179_91C9_A2FA_00000F317028 = Internal.createUniqueKey(WithinRepStat.WITHIN_REP_STAT, DSL.name("SQL0000000089-62a30128-0179-91c9-a2fa-00000f317028"), new TableField[] { WithinRepStat.WITHIN_REP_STAT.ID }, true);
    public static final UniqueKey<WithinRepStatRecord> WRS_UNIQUE_ELEMENT_SIMRUN_REPNUM = Internal.createUniqueKey(WithinRepStat.WITHIN_REP_STAT, DSL.name("WRS_UNIQUE_ELEMENT_SIMRUN_REPNUM"), new TableField[] { WithinRepStat.WITHIN_REP_STAT.ELEMENT_ID_FK, WithinRepStat.WITHIN_REP_STAT.SIM_RUN_ID_FK, WithinRepStat.WITHIN_REP_STAT.REP_NUM }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AcrossRepStatRecord, ModelElementRecord> ARS_MODEL_ELEMENT_FK = Internal.createForeignKey(AcrossRepStat.ACROSS_REP_STAT, DSL.name("ARS_MODEL_ELEMENT_FK"), new TableField[] { AcrossRepStat.ACROSS_REP_STAT.SIM_RUN_ID_FK, AcrossRepStat.ACROSS_REP_STAT.ELEMENT_ID_FK }, Keys.ME_PRIM_KY, new TableField[] { ModelElement.MODEL_ELEMENT.SIM_RUN_ID_FK, ModelElement.MODEL_ELEMENT.ELEMENT_ID }, true);
    public static final ForeignKey<AcrossRepStatRecord, SimulationRunRecord> ARS_SIMRUN_FK = Internal.createForeignKey(AcrossRepStat.ACROSS_REP_STAT, DSL.name("ARS_SIMRUN_FK"), new TableField[] { AcrossRepStat.ACROSS_REP_STAT.SIM_RUN_ID_FK }, Keys.SQL0000000081_7FA040FF_0179_91C9_A2FA_00000F317028, new TableField[] { SimulationRun.SIMULATION_RUN.ID }, true);
    public static final ForeignKey<BatchStatRecord, ModelElementRecord> BS_MODEL_ELEMENT_FK = Internal.createForeignKey(BatchStat.BATCH_STAT, DSL.name("BS_MODEL_ELEMENT_FK"), new TableField[] { BatchStat.BATCH_STAT.SIM_RUN_ID_FK, BatchStat.BATCH_STAT.ELEMENT_ID_FK }, Keys.ME_PRIM_KY, new TableField[] { ModelElement.MODEL_ELEMENT.SIM_RUN_ID_FK, ModelElement.MODEL_ELEMENT.ELEMENT_ID }, true);
    public static final ForeignKey<BatchStatRecord, SimulationRunRecord> BS_SIMRUN_FK = Internal.createForeignKey(BatchStat.BATCH_STAT, DSL.name("BS_SIMRUN_FK"), new TableField[] { BatchStat.BATCH_STAT.SIM_RUN_ID_FK }, Keys.SQL0000000081_7FA040FF_0179_91C9_A2FA_00000F317028, new TableField[] { SimulationRun.SIMULATION_RUN.ID }, true);
    public static final ForeignKey<ModelElementRecord, SimulationRunRecord> ME_SIMRUN_FK = Internal.createForeignKey(ModelElement.MODEL_ELEMENT, DSL.name("ME_SIMRUN_FK"), new TableField[] { ModelElement.MODEL_ELEMENT.SIM_RUN_ID_FK }, Keys.SQL0000000081_7FA040FF_0179_91C9_A2FA_00000F317028, new TableField[] { SimulationRun.SIMULATION_RUN.ID }, true);
    public static final ForeignKey<WithinRepCounterStatRecord, ModelElementRecord> WRCS_MODEL_ELEMENT_FK = Internal.createForeignKey(WithinRepCounterStat.WITHIN_REP_COUNTER_STAT, DSL.name("WRCS_MODEL_ELEMENT_FK"), new TableField[] { WithinRepCounterStat.WITHIN_REP_COUNTER_STAT.SIM_RUN_ID_FK, WithinRepCounterStat.WITHIN_REP_COUNTER_STAT.ELEMENT_ID_FK }, Keys.ME_PRIM_KY, new TableField[] { ModelElement.MODEL_ELEMENT.SIM_RUN_ID_FK, ModelElement.MODEL_ELEMENT.ELEMENT_ID }, true);
    public static final ForeignKey<WithinRepCounterStatRecord, SimulationRunRecord> WRCS_SIMRUN_FK = Internal.createForeignKey(WithinRepCounterStat.WITHIN_REP_COUNTER_STAT, DSL.name("WRCS_SIMRUN_FK"), new TableField[] { WithinRepCounterStat.WITHIN_REP_COUNTER_STAT.SIM_RUN_ID_FK }, Keys.SQL0000000081_7FA040FF_0179_91C9_A2FA_00000F317028, new TableField[] { SimulationRun.SIMULATION_RUN.ID }, true);
    public static final ForeignKey<WithinRepStatRecord, ModelElementRecord> WRS_MODEL_ELEMENT_FK = Internal.createForeignKey(WithinRepStat.WITHIN_REP_STAT, DSL.name("WRS_MODEL_ELEMENT_FK"), new TableField[] { WithinRepStat.WITHIN_REP_STAT.SIM_RUN_ID_FK, WithinRepStat.WITHIN_REP_STAT.ELEMENT_ID_FK }, Keys.ME_PRIM_KY, new TableField[] { ModelElement.MODEL_ELEMENT.SIM_RUN_ID_FK, ModelElement.MODEL_ELEMENT.ELEMENT_ID }, true);
    public static final ForeignKey<WithinRepStatRecord, SimulationRunRecord> WRS_SIMRUN_FK = Internal.createForeignKey(WithinRepStat.WITHIN_REP_STAT, DSL.name("WRS_SIMRUN_FK"), new TableField[] { WithinRepStat.WITHIN_REP_STAT.SIM_RUN_ID_FK }, Keys.SQL0000000081_7FA040FF_0179_91C9_A2FA_00000F317028, new TableField[] { SimulationRun.SIMULATION_RUN.ID }, true);
}
