/*
 * This file is generated by jOOQ.
 */
package jslx.dbutilities.jsldbsrc;


import jslx.dbutilities.jsldbsrc.tables.AcrossRepStat;
import jslx.dbutilities.jsldbsrc.tables.AcrossRepView;
import jslx.dbutilities.jsldbsrc.tables.BatchStat;
import jslx.dbutilities.jsldbsrc.tables.BatchStatView;
import jslx.dbutilities.jsldbsrc.tables.ModelElement;
import jslx.dbutilities.jsldbsrc.tables.PwDiffWithinRepView;
import jslx.dbutilities.jsldbsrc.tables.SimulationRun;
import jslx.dbutilities.jsldbsrc.tables.WithinRepCounterStat;
import jslx.dbutilities.jsldbsrc.tables.WithinRepCounterView;
import jslx.dbutilities.jsldbsrc.tables.WithinRepResponseView;
import jslx.dbutilities.jsldbsrc.tables.WithinRepStat;
import jslx.dbutilities.jsldbsrc.tables.WithinRepView;


/**
 * Convenience access to all tables in JSL_DB.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>JSL_DB.ACROSS_REP_STAT</code>.
     */
    public static final AcrossRepStat ACROSS_REP_STAT = AcrossRepStat.ACROSS_REP_STAT;

    /**
     * The table <code>JSL_DB.ACROSS_REP_VIEW</code>.
     */
    public static final AcrossRepView ACROSS_REP_VIEW = AcrossRepView.ACROSS_REP_VIEW;

    /**
     * The table <code>JSL_DB.BATCH_STAT</code>.
     */
    public static final BatchStat BATCH_STAT = BatchStat.BATCH_STAT;

    /**
     * The table <code>JSL_DB.BATCH_STAT_VIEW</code>.
     */
    public static final BatchStatView BATCH_STAT_VIEW = BatchStatView.BATCH_STAT_VIEW;

    /**
     * The table <code>JSL_DB.MODEL_ELEMENT</code>.
     */
    public static final ModelElement MODEL_ELEMENT = ModelElement.MODEL_ELEMENT;

    /**
     * The table <code>JSL_DB.PW_DIFF_WITHIN_REP_VIEW</code>.
     */
    public static final PwDiffWithinRepView PW_DIFF_WITHIN_REP_VIEW = PwDiffWithinRepView.PW_DIFF_WITHIN_REP_VIEW;

    /**
     * The table <code>JSL_DB.SIMULATION_RUN</code>.
     */
    public static final SimulationRun SIMULATION_RUN = SimulationRun.SIMULATION_RUN;

    /**
     * The table <code>JSL_DB.WITHIN_REP_COUNTER_STAT</code>.
     */
    public static final WithinRepCounterStat WITHIN_REP_COUNTER_STAT = WithinRepCounterStat.WITHIN_REP_COUNTER_STAT;

    /**
     * The table <code>JSL_DB.WITHIN_REP_COUNTER_VIEW</code>.
     */
    public static final WithinRepCounterView WITHIN_REP_COUNTER_VIEW = WithinRepCounterView.WITHIN_REP_COUNTER_VIEW;

    /**
     * The table <code>JSL_DB.WITHIN_REP_RESPONSE_VIEW</code>.
     */
    public static final WithinRepResponseView WITHIN_REP_RESPONSE_VIEW = WithinRepResponseView.WITHIN_REP_RESPONSE_VIEW;

    /**
     * The table <code>JSL_DB.WITHIN_REP_STAT</code>.
     */
    public static final WithinRepStat WITHIN_REP_STAT = WithinRepStat.WITHIN_REP_STAT;

    /**
     * The table <code>JSL_DB.WITHIN_REP_VIEW</code>.
     */
    public static final WithinRepView WITHIN_REP_VIEW = WithinRepView.WITHIN_REP_VIEW;
}
