/*
 * This file is generated by jOOQ.
 */
package jslx.dbutilities.jsldbsrc.tables.records;


import jslx.dbutilities.jsldbsrc.tables.PwDiffWithinRepView;

import org.jooq.Field;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PwDiffWithinRepViewRecord extends TableRecordImpl<PwDiffWithinRepViewRecord> implements Record11<String, Integer, String, String, Integer, Double, Integer, String, Double, String, Double> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>JSL_DB.PW_DIFF_WITHIN_REP_VIEW.SIM_NAME</code>.
     */
    public void setSimName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>JSL_DB.PW_DIFF_WITHIN_REP_VIEW.SIM_NAME</code>.
     */
    public String getSimName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>JSL_DB.PW_DIFF_WITHIN_REP_VIEW.A_SIM_NUM</code>.
     */
    public void setASimNum(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>JSL_DB.PW_DIFF_WITHIN_REP_VIEW.A_SIM_NUM</code>.
     */
    public Integer getASimNum() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>JSL_DB.PW_DIFF_WITHIN_REP_VIEW.STAT_NAME</code>.
     */
    public void setStatName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>JSL_DB.PW_DIFF_WITHIN_REP_VIEW.STAT_NAME</code>.
     */
    public String getStatName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>JSL_DB.PW_DIFF_WITHIN_REP_VIEW.A_EXP_NAME</code>.
     */
    public void setAExpName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>JSL_DB.PW_DIFF_WITHIN_REP_VIEW.A_EXP_NAME</code>.
     */
    public String getAExpName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>JSL_DB.PW_DIFF_WITHIN_REP_VIEW.REP_NUM</code>.
     */
    public void setRepNum(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>JSL_DB.PW_DIFF_WITHIN_REP_VIEW.REP_NUM</code>.
     */
    public Integer getRepNum() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>JSL_DB.PW_DIFF_WITHIN_REP_VIEW.A_VALUE</code>.
     */
    public void setAValue(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>JSL_DB.PW_DIFF_WITHIN_REP_VIEW.A_VALUE</code>.
     */
    public Double getAValue() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>JSL_DB.PW_DIFF_WITHIN_REP_VIEW.B_SIM_NUM</code>.
     */
    public void setBSimNum(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>JSL_DB.PW_DIFF_WITHIN_REP_VIEW.B_SIM_NUM</code>.
     */
    public Integer getBSimNum() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>JSL_DB.PW_DIFF_WITHIN_REP_VIEW.B_EXP_NAME</code>.
     */
    public void setBExpName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>JSL_DB.PW_DIFF_WITHIN_REP_VIEW.B_EXP_NAME</code>.
     */
    public String getBExpName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>JSL_DB.PW_DIFF_WITHIN_REP_VIEW.B_VALUE</code>.
     */
    public void setBValue(Double value) {
        set(8, value);
    }

    /**
     * Getter for <code>JSL_DB.PW_DIFF_WITHIN_REP_VIEW.B_VALUE</code>.
     */
    public Double getBValue() {
        return (Double) get(8);
    }

    /**
     * Setter for <code>JSL_DB.PW_DIFF_WITHIN_REP_VIEW.DIFF_NAME</code>.
     */
    public void setDiffName(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>JSL_DB.PW_DIFF_WITHIN_REP_VIEW.DIFF_NAME</code>.
     */
    public String getDiffName() {
        return (String) get(9);
    }

    /**
     * Setter for <code>JSL_DB.PW_DIFF_WITHIN_REP_VIEW.A_MINUS_B</code>.
     */
    public void setAMinusB(Double value) {
        set(10, value);
    }

    /**
     * Getter for <code>JSL_DB.PW_DIFF_WITHIN_REP_VIEW.A_MINUS_B</code>.
     */
    public Double getAMinusB() {
        return (Double) get(10);
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<String, Integer, String, String, Integer, Double, Integer, String, Double, String, Double> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<String, Integer, String, String, Integer, Double, Integer, String, Double, String, Double> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return PwDiffWithinRepView.PW_DIFF_WITHIN_REP_VIEW.SIM_NAME;
    }

    @Override
    public Field<Integer> field2() {
        return PwDiffWithinRepView.PW_DIFF_WITHIN_REP_VIEW.A_SIM_NUM;
    }

    @Override
    public Field<String> field3() {
        return PwDiffWithinRepView.PW_DIFF_WITHIN_REP_VIEW.STAT_NAME;
    }

    @Override
    public Field<String> field4() {
        return PwDiffWithinRepView.PW_DIFF_WITHIN_REP_VIEW.A_EXP_NAME;
    }

    @Override
    public Field<Integer> field5() {
        return PwDiffWithinRepView.PW_DIFF_WITHIN_REP_VIEW.REP_NUM;
    }

    @Override
    public Field<Double> field6() {
        return PwDiffWithinRepView.PW_DIFF_WITHIN_REP_VIEW.A_VALUE;
    }

    @Override
    public Field<Integer> field7() {
        return PwDiffWithinRepView.PW_DIFF_WITHIN_REP_VIEW.B_SIM_NUM;
    }

    @Override
    public Field<String> field8() {
        return PwDiffWithinRepView.PW_DIFF_WITHIN_REP_VIEW.B_EXP_NAME;
    }

    @Override
    public Field<Double> field9() {
        return PwDiffWithinRepView.PW_DIFF_WITHIN_REP_VIEW.B_VALUE;
    }

    @Override
    public Field<String> field10() {
        return PwDiffWithinRepView.PW_DIFF_WITHIN_REP_VIEW.DIFF_NAME;
    }

    @Override
    public Field<Double> field11() {
        return PwDiffWithinRepView.PW_DIFF_WITHIN_REP_VIEW.A_MINUS_B;
    }

    @Override
    public String component1() {
        return getSimName();
    }

    @Override
    public Integer component2() {
        return getASimNum();
    }

    @Override
    public String component3() {
        return getStatName();
    }

    @Override
    public String component4() {
        return getAExpName();
    }

    @Override
    public Integer component5() {
        return getRepNum();
    }

    @Override
    public Double component6() {
        return getAValue();
    }

    @Override
    public Integer component7() {
        return getBSimNum();
    }

    @Override
    public String component8() {
        return getBExpName();
    }

    @Override
    public Double component9() {
        return getBValue();
    }

    @Override
    public String component10() {
        return getDiffName();
    }

    @Override
    public Double component11() {
        return getAMinusB();
    }

    @Override
    public String value1() {
        return getSimName();
    }

    @Override
    public Integer value2() {
        return getASimNum();
    }

    @Override
    public String value3() {
        return getStatName();
    }

    @Override
    public String value4() {
        return getAExpName();
    }

    @Override
    public Integer value5() {
        return getRepNum();
    }

    @Override
    public Double value6() {
        return getAValue();
    }

    @Override
    public Integer value7() {
        return getBSimNum();
    }

    @Override
    public String value8() {
        return getBExpName();
    }

    @Override
    public Double value9() {
        return getBValue();
    }

    @Override
    public String value10() {
        return getDiffName();
    }

    @Override
    public Double value11() {
        return getAMinusB();
    }

    @Override
    public PwDiffWithinRepViewRecord value1(String value) {
        setSimName(value);
        return this;
    }

    @Override
    public PwDiffWithinRepViewRecord value2(Integer value) {
        setASimNum(value);
        return this;
    }

    @Override
    public PwDiffWithinRepViewRecord value3(String value) {
        setStatName(value);
        return this;
    }

    @Override
    public PwDiffWithinRepViewRecord value4(String value) {
        setAExpName(value);
        return this;
    }

    @Override
    public PwDiffWithinRepViewRecord value5(Integer value) {
        setRepNum(value);
        return this;
    }

    @Override
    public PwDiffWithinRepViewRecord value6(Double value) {
        setAValue(value);
        return this;
    }

    @Override
    public PwDiffWithinRepViewRecord value7(Integer value) {
        setBSimNum(value);
        return this;
    }

    @Override
    public PwDiffWithinRepViewRecord value8(String value) {
        setBExpName(value);
        return this;
    }

    @Override
    public PwDiffWithinRepViewRecord value9(Double value) {
        setBValue(value);
        return this;
    }

    @Override
    public PwDiffWithinRepViewRecord value10(String value) {
        setDiffName(value);
        return this;
    }

    @Override
    public PwDiffWithinRepViewRecord value11(Double value) {
        setAMinusB(value);
        return this;
    }

    @Override
    public PwDiffWithinRepViewRecord values(String value1, Integer value2, String value3, String value4, Integer value5, Double value6, Integer value7, String value8, Double value9, String value10, Double value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PwDiffWithinRepViewRecord
     */
    public PwDiffWithinRepViewRecord() {
        super(PwDiffWithinRepView.PW_DIFF_WITHIN_REP_VIEW);
    }

    /**
     * Create a detached, initialised PwDiffWithinRepViewRecord
     */
    public PwDiffWithinRepViewRecord(String simName, Integer aSimNum, String statName, String aExpName, Integer repNum, Double aValue, Integer bSimNum, String bExpName, Double bValue, String diffName, Double aMinusB) {
        super(PwDiffWithinRepView.PW_DIFF_WITHIN_REP_VIEW);

        setSimName(simName);
        setASimNum(aSimNum);
        setStatName(statName);
        setAExpName(aExpName);
        setRepNum(repNum);
        setAValue(aValue);
        setBSimNum(bSimNum);
        setBExpName(bExpName);
        setBValue(bValue);
        setDiffName(diffName);
        setAMinusB(aMinusB);
    }
}
