/*
 * This file is generated by jOOQ.
 */
package jslx.dbutilities.jsldbsrc.tables;


import jslx.dbutilities.jsldbsrc.JslDb;
import jslx.dbutilities.jsldbsrc.tables.records.BatchStatViewRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BatchStatView extends TableImpl<BatchStatViewRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>JSL_DB.BATCH_STAT_VIEW</code>
     */
    public static final BatchStatView BATCH_STAT_VIEW = new BatchStatView();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BatchStatViewRecord> getRecordType() {
        return BatchStatViewRecord.class;
    }

    /**
     * The column <code>JSL_DB.BATCH_STAT_VIEW.SIM_RUN_ID_FK</code>.
     */
    public final TableField<BatchStatViewRecord, Integer> SIM_RUN_ID_FK = createField(DSL.name("SIM_RUN_ID_FK"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>JSL_DB.BATCH_STAT_VIEW.EXP_NAME</code>.
     */
    public final TableField<BatchStatViewRecord, String> EXP_NAME = createField(DSL.name("EXP_NAME"), SQLDataType.VARCHAR(510).nullable(false), this, "");

    /**
     * The column <code>JSL_DB.BATCH_STAT_VIEW.STAT_NAME</code>.
     */
    public final TableField<BatchStatViewRecord, String> STAT_NAME = createField(DSL.name("STAT_NAME"), SQLDataType.VARCHAR(510), this, "");

    /**
     * The column <code>JSL_DB.BATCH_STAT_VIEW.STAT_COUNT</code>.
     */
    public final TableField<BatchStatViewRecord, Double> STAT_COUNT = createField(DSL.name("STAT_COUNT"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>JSL_DB.BATCH_STAT_VIEW.AVERAGE</code>.
     */
    public final TableField<BatchStatViewRecord, Double> AVERAGE = createField(DSL.name("AVERAGE"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>JSL_DB.BATCH_STAT_VIEW.STD_DEV</code>.
     */
    public final TableField<BatchStatViewRecord, Double> STD_DEV = createField(DSL.name("STD_DEV"), SQLDataType.DOUBLE, this, "");

    private BatchStatView(Name alias, Table<BatchStatViewRecord> aliased) {
        this(alias, aliased, null);
    }

    private BatchStatView(Name alias, Table<BatchStatViewRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("CREATE VIEW JSL_DB.BATCH_STAT_VIEW (SIM_RUN_ID_FK, EXP_NAME, STAT_NAME, STAT_COUNT, AVERAGE, STD_DEV) AS (SELECT JSL_DB.BATCH_STAT.SIM_RUN_ID_FK, EXP_NAME, STAT_NAME, STAT_COUNT, AVERAGE, STD_DEV FROM JSL_DB.SIMULATION_RUN, JSL_DB.BATCH_STAT, JSL_DB.MODEL_ELEMENT WHERE JSL_DB.SIMULATION_RUN.ID = JSL_DB.BATCH_STAT.SIM_RUN_ID_FK AND JSL_DB.SIMULATION_RUN.ID = JSL_DB.MODEL_ELEMENT.SIM_RUN_ID_FK AND JSL_DB.MODEL_ELEMENT.ELEMENT_ID = JSL_DB.BATCH_STAT.ELEMENT_ID_FK AND JSL_DB.MODEL_ELEMENT.ELEMENT_NAME = JSL_DB.BATCH_STAT.STAT_NAME ORDER BY STAT_NAME,JSL_DB.BATCH_STAT.SIM_RUN_ID_FK, EXP_NAME)"));
    }

    /**
     * Create an aliased <code>JSL_DB.BATCH_STAT_VIEW</code> table reference
     */
    public BatchStatView(String alias) {
        this(DSL.name(alias), BATCH_STAT_VIEW);
    }

    /**
     * Create an aliased <code>JSL_DB.BATCH_STAT_VIEW</code> table reference
     */
    public BatchStatView(Name alias) {
        this(alias, BATCH_STAT_VIEW);
    }

    /**
     * Create a <code>JSL_DB.BATCH_STAT_VIEW</code> table reference
     */
    public BatchStatView() {
        this(DSL.name("BATCH_STAT_VIEW"), null);
    }

    public <O extends Record> BatchStatView(Table<O> child, ForeignKey<O, BatchStatViewRecord> key) {
        super(child, key, BATCH_STAT_VIEW);
    }

    @Override
    public Schema getSchema() {
        return JslDb.JSL_DB;
    }

    @Override
    public BatchStatView as(String alias) {
        return new BatchStatView(DSL.name(alias), this);
    }

    @Override
    public BatchStatView as(Name alias) {
        return new BatchStatView(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public BatchStatView rename(String name) {
        return new BatchStatView(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BatchStatView rename(Name name) {
        return new BatchStatView(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, Double, Double, Double> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
