/*
 * This file is generated by jOOQ.
 */
package jslx.dbutilities.jsldbsrc.tables;


import jslx.dbutilities.jsldbsrc.JslDb;
import jslx.dbutilities.jsldbsrc.tables.records.WithinRepViewRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WithinRepView extends TableImpl<WithinRepViewRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>JSL_DB.WITHIN_REP_VIEW</code>
     */
    public static final WithinRepView WITHIN_REP_VIEW = new WithinRepView();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WithinRepViewRecord> getRecordType() {
        return WithinRepViewRecord.class;
    }

    /**
     * The column <code>JSL_DB.WITHIN_REP_VIEW.SIM_RUN_ID_FK</code>.
     */
    public final TableField<WithinRepViewRecord, Integer> SIM_RUN_ID_FK = createField(DSL.name("SIM_RUN_ID_FK"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>JSL_DB.WITHIN_REP_VIEW.EXP_NAME</code>.
     */
    public final TableField<WithinRepViewRecord, String> EXP_NAME = createField(DSL.name("EXP_NAME"), SQLDataType.VARCHAR(510).nullable(false), this, "");

    /**
     * The column <code>JSL_DB.WITHIN_REP_VIEW.STAT_NAME</code>.
     */
    public final TableField<WithinRepViewRecord, String> STAT_NAME = createField(DSL.name("STAT_NAME"), SQLDataType.VARCHAR(510), this, "");

    /**
     * The column <code>JSL_DB.WITHIN_REP_VIEW.REP_NUM</code>.
     */
    public final TableField<WithinRepViewRecord, Integer> REP_NUM = createField(DSL.name("REP_NUM"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>JSL_DB.WITHIN_REP_VIEW.VALUE</code>.
     */
    public final TableField<WithinRepViewRecord, Double> VALUE = createField(DSL.name("VALUE"), SQLDataType.DOUBLE, this, "");

    private WithinRepView(Name alias, Table<WithinRepViewRecord> aliased) {
        this(alias, aliased, null);
    }

    private WithinRepView(Name alias, Table<WithinRepViewRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("CREATE VIEW JSL_DB.WITHIN_REP_VIEW (SIM_RUN_ID_FK, EXP_NAME, STAT_NAME, REP_NUM, VALUE) AS (SELECT SIM_RUN_ID_FK, EXP_NAME, STAT_NAME, REP_NUM, AVERAGE AS VALUE FROM JSL_DB.WITHIN_REP_RESPONSE_VIEW UNION SELECT SIM_RUN_ID_FK, EXP_NAME, STAT_NAME, REP_NUM, LAST_VALUE AS VALUE FROM JSL_DB.WITHIN_REP_COUNTER_VIEW)"));
    }

    /**
     * Create an aliased <code>JSL_DB.WITHIN_REP_VIEW</code> table reference
     */
    public WithinRepView(String alias) {
        this(DSL.name(alias), WITHIN_REP_VIEW);
    }

    /**
     * Create an aliased <code>JSL_DB.WITHIN_REP_VIEW</code> table reference
     */
    public WithinRepView(Name alias) {
        this(alias, WITHIN_REP_VIEW);
    }

    /**
     * Create a <code>JSL_DB.WITHIN_REP_VIEW</code> table reference
     */
    public WithinRepView() {
        this(DSL.name("WITHIN_REP_VIEW"), null);
    }

    public <O extends Record> WithinRepView(Table<O> child, ForeignKey<O, WithinRepViewRecord> key) {
        super(child, key, WITHIN_REP_VIEW);
    }

    @Override
    public Schema getSchema() {
        return JslDb.JSL_DB;
    }

    @Override
    public WithinRepView as(String alias) {
        return new WithinRepView(DSL.name(alias), this);
    }

    @Override
    public WithinRepView as(Name alias) {
        return new WithinRepView(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public WithinRepView rename(String name) {
        return new WithinRepView(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WithinRepView rename(Name name) {
        return new WithinRepView(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, Integer, Double> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
