/*
 * This file is generated by jOOQ.
 */
package jslx.dbutilities.jsldbsrc.tables;


import jslx.dbutilities.jsldbsrc.JslDb;
import jslx.dbutilities.jsldbsrc.tables.records.WithinRepCounterViewRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WithinRepCounterView extends TableImpl<WithinRepCounterViewRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>JSL_DB.WITHIN_REP_COUNTER_VIEW</code>
     */
    public static final WithinRepCounterView WITHIN_REP_COUNTER_VIEW = new WithinRepCounterView();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WithinRepCounterViewRecord> getRecordType() {
        return WithinRepCounterViewRecord.class;
    }

    /**
     * The column <code>JSL_DB.WITHIN_REP_COUNTER_VIEW.SIM_RUN_ID_FK</code>.
     */
    public final TableField<WithinRepCounterViewRecord, Integer> SIM_RUN_ID_FK = createField(DSL.name("SIM_RUN_ID_FK"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>JSL_DB.WITHIN_REP_COUNTER_VIEW.EXP_NAME</code>.
     */
    public final TableField<WithinRepCounterViewRecord, String> EXP_NAME = createField(DSL.name("EXP_NAME"), SQLDataType.VARCHAR(510).nullable(false), this, "");

    /**
     * The column <code>JSL_DB.WITHIN_REP_COUNTER_VIEW.STAT_NAME</code>.
     */
    public final TableField<WithinRepCounterViewRecord, String> STAT_NAME = createField(DSL.name("STAT_NAME"), SQLDataType.VARCHAR(510), this, "");

    /**
     * The column <code>JSL_DB.WITHIN_REP_COUNTER_VIEW.REP_NUM</code>.
     */
    public final TableField<WithinRepCounterViewRecord, Integer> REP_NUM = createField(DSL.name("REP_NUM"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>JSL_DB.WITHIN_REP_COUNTER_VIEW.LAST_VALUE</code>.
     */
    public final TableField<WithinRepCounterViewRecord, Double> LAST_VALUE = createField(DSL.name("LAST_VALUE"), SQLDataType.DOUBLE, this, "");

    private WithinRepCounterView(Name alias, Table<WithinRepCounterViewRecord> aliased) {
        this(alias, aliased, null);
    }

    private WithinRepCounterView(Name alias, Table<WithinRepCounterViewRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("CREATE VIEW JSL_DB.WITHIN_REP_COUNTER_VIEW (SIM_RUN_ID_FK, EXP_NAME, STAT_NAME, REP_NUM, LAST_VALUE) AS (SELECT JSL_DB.WITHIN_REP_COUNTER_STAT.SIM_RUN_ID_FK, EXP_NAME, STAT_NAME, REP_NUM, LAST_VALUE FROM JSL_DB.SIMULATION_RUN, JSL_DB.WITHIN_REP_COUNTER_STAT, JSL_DB.MODEL_ELEMENT WHERE JSL_DB.SIMULATION_RUN.ID = JSL_DB.WITHIN_REP_COUNTER_STAT.SIM_RUN_ID_FK AND JSL_DB.SIMULATION_RUN.ID = JSL_DB.MODEL_ELEMENT.SIM_RUN_ID_FK AND JSL_DB.MODEL_ELEMENT.ELEMENT_ID = JSL_DB.WITHIN_REP_COUNTER_STAT.ELEMENT_ID_FK AND JSL_DB.MODEL_ELEMENT.ELEMENT_NAME = JSL_DB.WITHIN_REP_COUNTER_STAT.STAT_NAME ORDER BY JSL_DB.WITHIN_REP_COUNTER_STAT.SIM_RUN_ID_FK, EXP_NAME, STAT_NAME, REP_NUM)"));
    }

    /**
     * Create an aliased <code>JSL_DB.WITHIN_REP_COUNTER_VIEW</code> table reference
     */
    public WithinRepCounterView(String alias) {
        this(DSL.name(alias), WITHIN_REP_COUNTER_VIEW);
    }

    /**
     * Create an aliased <code>JSL_DB.WITHIN_REP_COUNTER_VIEW</code> table reference
     */
    public WithinRepCounterView(Name alias) {
        this(alias, WITHIN_REP_COUNTER_VIEW);
    }

    /**
     * Create a <code>JSL_DB.WITHIN_REP_COUNTER_VIEW</code> table reference
     */
    public WithinRepCounterView() {
        this(DSL.name("WITHIN_REP_COUNTER_VIEW"), null);
    }

    public <O extends Record> WithinRepCounterView(Table<O> child, ForeignKey<O, WithinRepCounterViewRecord> key) {
        super(child, key, WITHIN_REP_COUNTER_VIEW);
    }

    @Override
    public Schema getSchema() {
        return JslDb.JSL_DB;
    }

    @Override
    public WithinRepCounterView as(String alias) {
        return new WithinRepCounterView(DSL.name(alias), this);
    }

    @Override
    public WithinRepCounterView as(Name alias) {
        return new WithinRepCounterView(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public WithinRepCounterView rename(String name) {
        return new WithinRepCounterView(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WithinRepCounterView rename(Name name) {
        return new WithinRepCounterView(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, Integer, Double> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
