/*
 * This file is generated by jOOQ.
 */
package jslx.dbutilities.jsldbsrc.tables;


import java.util.Arrays;
import java.util.List;

import jslx.dbutilities.jsldbsrc.JslDb;
import jslx.dbutilities.jsldbsrc.Keys;
import jslx.dbutilities.jsldbsrc.tables.records.WithinRepCounterStatRecord;

import org.jooq.Check;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WithinRepCounterStat extends TableImpl<WithinRepCounterStatRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>JSL_DB.WITHIN_REP_COUNTER_STAT</code>
     */
    public static final WithinRepCounterStat WITHIN_REP_COUNTER_STAT = new WithinRepCounterStat();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WithinRepCounterStatRecord> getRecordType() {
        return WithinRepCounterStatRecord.class;
    }

    /**
     * The column <code>JSL_DB.WITHIN_REP_COUNTER_STAT.ID</code>.
     */
    public final TableField<WithinRepCounterStatRecord, Integer> ID = createField(DSL.name("ID"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>JSL_DB.WITHIN_REP_COUNTER_STAT.ELEMENT_ID_FK</code>.
     */
    public final TableField<WithinRepCounterStatRecord, Integer> ELEMENT_ID_FK = createField(DSL.name("ELEMENT_ID_FK"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>JSL_DB.WITHIN_REP_COUNTER_STAT.SIM_RUN_ID_FK</code>.
     */
    public final TableField<WithinRepCounterStatRecord, Integer> SIM_RUN_ID_FK = createField(DSL.name("SIM_RUN_ID_FK"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>JSL_DB.WITHIN_REP_COUNTER_STAT.REP_NUM</code>.
     */
    public final TableField<WithinRepCounterStatRecord, Integer> REP_NUM = createField(DSL.name("REP_NUM"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>JSL_DB.WITHIN_REP_COUNTER_STAT.STAT_NAME</code>.
     */
    public final TableField<WithinRepCounterStatRecord, String> STAT_NAME = createField(DSL.name("STAT_NAME"), SQLDataType.VARCHAR(510), this, "");

    /**
     * The column <code>JSL_DB.WITHIN_REP_COUNTER_STAT.LAST_VALUE</code>.
     */
    public final TableField<WithinRepCounterStatRecord, Double> LAST_VALUE = createField(DSL.name("LAST_VALUE"), SQLDataType.DOUBLE, this, "");

    private WithinRepCounterStat(Name alias, Table<WithinRepCounterStatRecord> aliased) {
        this(alias, aliased, null);
    }

    private WithinRepCounterStat(Name alias, Table<WithinRepCounterStatRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>JSL_DB.WITHIN_REP_COUNTER_STAT</code> table reference
     */
    public WithinRepCounterStat(String alias) {
        this(DSL.name(alias), WITHIN_REP_COUNTER_STAT);
    }

    /**
     * Create an aliased <code>JSL_DB.WITHIN_REP_COUNTER_STAT</code> table reference
     */
    public WithinRepCounterStat(Name alias) {
        this(alias, WITHIN_REP_COUNTER_STAT);
    }

    /**
     * Create a <code>JSL_DB.WITHIN_REP_COUNTER_STAT</code> table reference
     */
    public WithinRepCounterStat() {
        this(DSL.name("WITHIN_REP_COUNTER_STAT"), null);
    }

    public <O extends Record> WithinRepCounterStat(Table<O> child, ForeignKey<O, WithinRepCounterStatRecord> key) {
        super(child, key, WITHIN_REP_COUNTER_STAT);
    }

    @Override
    public Schema getSchema() {
        return JslDb.JSL_DB;
    }

    @Override
    public Identity<WithinRepCounterStatRecord, Integer> getIdentity() {
        return (Identity<WithinRepCounterStatRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<WithinRepCounterStatRecord> getPrimaryKey() {
        return Keys.SQL0000000102_C5044162_0179_91C9_A2FA_00000F317028;
    }

    @Override
    public List<UniqueKey<WithinRepCounterStatRecord>> getKeys() {
        return Arrays.<UniqueKey<WithinRepCounterStatRecord>>asList(Keys.SQL0000000102_C5044162_0179_91C9_A2FA_00000F317028, Keys.WRCS_UNIQUE_ELEMENT_SIMRUN_REPNUM);
    }

    @Override
    public List<ForeignKey<WithinRepCounterStatRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<WithinRepCounterStatRecord, ?>>asList(Keys.WRCS_MODEL_ELEMENT_FK, Keys.WRCS_SIMRUN_FK);
    }

    private transient ModelElement _modelElement;
    private transient SimulationRun _simulationRun;

    public ModelElement modelElement() {
        if (_modelElement == null)
            _modelElement = new ModelElement(this, Keys.WRCS_MODEL_ELEMENT_FK);

        return _modelElement;
    }

    public SimulationRun simulationRun() {
        if (_simulationRun == null)
            _simulationRun = new SimulationRun(this, Keys.WRCS_SIMRUN_FK);

        return _simulationRun;
    }

    @Override
    public List<Check<WithinRepCounterStatRecord>> getChecks() {
        return Arrays.<Check<WithinRepCounterStatRecord>>asList(
              Internal.createCheck(this, DSL.name("SQL0000000103-dd5cc163-0179-91c9-a2fa-00000f317028"), "(REP_NUM >=1)", true)
        );
    }

    @Override
    public WithinRepCounterStat as(String alias) {
        return new WithinRepCounterStat(DSL.name(alias), this);
    }

    @Override
    public WithinRepCounterStat as(Name alias) {
        return new WithinRepCounterStat(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public WithinRepCounterStat rename(String name) {
        return new WithinRepCounterStat(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WithinRepCounterStat rename(Name name) {
        return new WithinRepCounterStat(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, Integer, Integer, String, Double> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
